#!/usr/bin/env bash
# Writes apps/web/.env.development.local with the local Supabase and Inngest
# settings. Keys for hosted services (Gemini, Anthropic) come from Vercel's
# Development environment via `vercel env pull apps/web/.env.local`; Next.js
# loads .env.development.local on top, so the two never overwrite each other.
set -euo pipefail

ROOT=$(git rev-parse --show-toplevel)
OUT="$ROOT/apps/web/.env.development.local"
cd "$ROOT"

status=$(pnpm exec supabase status -o env 2>/dev/null) || {
  echo "Supabase local no está corriendo. Corré: pnpm exec supabase start" >&2
  exit 1
}

value() {
  printf '%s\n' "$status" | sed -n "s/^$1=\"\{0,1\}\([^\"]*\)\"\{0,1\}$/\1/p"
}

umask 077
cat > "$OUT" <<ENV
# Generated by pnpm env:local. Do not edit or commit.
NEXT_PUBLIC_SUPABASE_URL=$(value API_URL)
NEXT_PUBLIC_SUPABASE_ANON_KEY=$(value ANON_KEY)
SUPABASE_SERVICE_ROLE_KEY=$(value SERVICE_ROLE_KEY)
INNGEST_DEV=1
ENV

echo "Wrote $OUT"
