#!/usr/bin/env bash
# Writes apps/web/.env.development.local with the local Supabase settings. Keys for hosted services (Gemini, Anthropic) come from Vercel's
# Development environment via `vercel env pull apps/web/.env.local`; Next.js
# loads .env.development.local on top, so the two never overwrite each other.
set -euo pipefail

ROOT=$(git rev-parse --show-toplevel)
OUT="$ROOT/apps/web/.env.development.local"
cd "$ROOT"

status=$(pnpm exec supabase status -o env 2>/dev/null) || {
  echo "Local Supabase is not running. Run: pnpm exec supabase start" >&2
  exit 1
}

value() {
  local v
  v=$(printf '%s\n' "$status" | sed -n "s/^$1=\"\{0,1\}\([^\"]*\)\"\{0,1\}$/\1/p")
  if [ -z "$v" ]; then
    echo "supabase status did not return $1" >&2
    exit 1
  fi
  printf '%s' "$v"
}

url=$(value API_URL)
anon=$(value ANON_KEY)
service=$(value SERVICE_ROLE_KEY)

# umask only applies to new files, so drop the old one first.
rm -f "$OUT"
umask 077
cat > "$OUT" <<ENV
# Generated by pnpm env:local. Do not edit or commit.
NEXT_PUBLIC_SUPABASE_URL=$url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon
SUPABASE_SERVICE_ROLE_KEY=$service
ENV

echo "Wrote $OUT"
