import { isInlineQrSvg, qrDataUrl, withQrSvgViewBox } from "./qr-svg";

// The opening tag of ajstarks/svgo Start() + goqrsvg StartQrSVG.
const GOTRUE_QR = `<?xml version="1.0"?>
<!-- Generated by SVGo -->
<svg width="123" height="123"
 xmlns="http://www.w3.org/2000/svg"
 xmlns:xlink="http://www.w3.org/1999/xlink">
<rect x="12" y="12" width="3" height="3" style="fill:black;stroke:none"/>
<rect x="15" y="12" width="3" height="3" style="fill:white;stroke:none"/>
</svg>`;

describe("withQrSvgViewBox", () => {
  it("adds viewBox from goqrsvg width/height and un-mirrors swapped module axes", () => {
    const scaled = withQrSvgViewBox(GOTRUE_QR);

    expect(scaled).toMatch(
      /^<svg viewBox="0 0 123 123" width="123" height="123"/,
    );
    expect(scaled).toContain(
      '<rect x="12" y="12" width="3" height="3" style="fill:black;stroke:none"/>',
    );
    // goqrsvg drew At(x=1, y=0) at SVG (15, 12); the camera needs (12, 15).
    expect(scaled).toContain(
      '<rect x="12" y="15" width="3" height="3" style="fill:white;stroke:none"/>',
    );
    expect(scaled).not.toContain(
      '<rect x="15" y="12" width="3" height="3" style="fill:white;stroke:none"/>',
    );
    expect(scaled.startsWith("<?xml")).toBe(false);
  });

  it("leaves an existing viewBox alone", () => {
    const withBox =
      '<svg width="123" height="123" viewBox="0 0 123 123"><rect width="3" height="3"/></svg>';
    expect(withQrSvgViewBox(withBox)).toBe(withBox);
  });

  it("passes through non-SVG markup", () => {
    const dataUri = "data:image/png;base64,abc";
    expect(withQrSvgViewBox(dataUri)).toBe(dataUri);
  });

  it("passes through SVG that has no width to copy", () => {
    const bare = "<svg><rect width='3' height='3'/></svg>";
    expect(withQrSvgViewBox(bare)).toBe(bare);
  });

  it("uses width when height is absent", () => {
    const svg =
      '<svg width="99"><rect x="1" y="0" width="3" height="3"/></svg>';
    expect(withQrSvgViewBox(svg)).toMatch(
      /^<svg viewBox="0 0 99 99" width="99"/,
    );
  });

  it("parses width and height with a px suffix", () => {
    const svg = '<svg width="50px" height="50px"></svg>';
    expect(withQrSvgViewBox(svg)).toMatch(/^<svg viewBox="0 0 50 50"/);
  });

  it("leaves on-diagonal rects unchanged", () => {
    const svg =
      '<svg width="10" height="10"><rect x="5" y="5" width="1" height="1"/></svg>';
    expect(withQrSvgViewBox(svg)).toContain('<rect x="5" y="5"');
  });

  it("swaps axes on single-quoted rect attributes", () => {
    const svg = `<svg width="10" height="10"><rect x='3' y='1' width="1" height="1"/></svg>`;
    expect(withQrSvgViewBox(svg)).toContain('<rect x="1" y="3"');
  });

  it("does not rewrite an inline SVG data URI", () => {
    const dataUri =
      'data:image/svg+xml,<svg width="123" height="123"><rect x="15" y="12" width="3" height="3"/></svg>';
    expect(isInlineQrSvg(dataUri)).toBe(false);
    expect(withQrSvgViewBox(dataUri)).toBe(dataUri);
  });
});

describe("isInlineQrSvg", () => {
  it("accepts Auth's XML-prefixed SVG and raw <svg>", () => {
    expect(isInlineQrSvg(GOTRUE_QR)).toBe(true);
    expect(isInlineQrSvg('<svg width="1" height="1"></svg>')).toBe(true);
  });

  it("rejects data URIs and empty markup", () => {
    expect(isInlineQrSvg("data:image/png;base64,abc")).toBe(false);
    expect(
      isInlineQrSvg("data:image/svg+xml,<svg width='1' height='1'></svg>"),
    ).toBe(false);
    expect(
      isInlineQrSvg("DATA:image/svg+xml,<svg width='1' height='1'></svg>"),
    ).toBe(false);
    expect(isInlineQrSvg("")).toBe(false);
    expect(isInlineQrSvg("   ")).toBe(false);
  });
});

describe("qrDataUrl", () => {
  it("encodes the markup into a data: URL an <img> can show", () => {
    const url = qrDataUrl('<svg width="1"><rect x="0"/></svg>');
    expect(url).toMatch(/^data:image\/svg\+xml;charset=utf-8,%3Csvg/);
    expect(decodeURIComponent(url.split(",")[1] ?? "")).toBe(
      '<svg width="1"><rect x="0"/></svg>',
    );
  });
});
